["Seller",
    {
      "name": "Pepes",
      "email": "pepespanaderia@gmail.com",
      "password": "123456",
      "address": "Moreno 546",
      "time": "10-10-2023",
      "average_rating": 3.5,
      "rating": [],
      "contact": "1125464597",
      "payment": "Efectivo",
      "image": null
    },
    {
      "name": "La Picantería",
      "email": "lapicanteria@gmail.com",
      "password": "password123",
      "address": "Av. Libertador 123",
      "time": "12-10-2023",
      "average_rating": 4.2,
      "rating": [],
      "contact": "1123456789",
      "payment": "Pago Online/Tarjeta",
      "image": null
    },
    {
      "name": "Don Empanadas",
      "email": "donempanadas@gmail.com",
      "password": "empanadas456",
      "address": "Calle Bolivar 789",
      "time": "11-10-2023",
      "average_rating": 4.0,
      "rating": [],
      "contact": "1122334455",
      "payment": "Efectivo",
      "image": null
    },
    {
      "name": "La Parrilla Criolla",
      "email": "laparrillacriolla@gmail.com",
      "password": "asado789",
      "address": "Av. San Martín 456",
      "time": "13-10-2023",
      "average_rating": 4.5,
      "rating": [],
      "contact": "1155667788",
      "payment": "Pago Online/Tarjeta",
      "image": null
    },
    {
      "name": "Sabores de Asia",
      "email": "saboresdeasia@gmail.com",
      "password": "asiatica123",
      "address": "Calle 123 Oriental",
      "time": "14-10-2023",
      "average_rating": 3.8,
      "rating": [],
      "contact": "1199887766",
      "payment": "Efectivo",
      "image": null
    },
    {
      "name": "Pasta y Amor",
      "email": "pastayamor@gmail.com",
      "password": "pastalover456",
      "address": "Av. Italia 789",
      "time": "15-10-2023",
      "average_rating": 4.2,
      "rating": [],
      "contact": "1144556677",
      "payment": "Pago Online/Tarjeta",
      "image": null
    },
    {
      "name": "Delicias del Mar",
      "email": "deliciasdelmar@gmail.com",
      "password": "mariscos123",
      "address": "Calle del Puerto 123",
      "time": "16-10-2023",
      "average_rating": 4.3,
      "rating": [],
      "contact": "1122998844",
      "payment": "Efectivo",
      "image": null
    },
    {
      "name": "La Cafetería",
      "email": "lacafeteria@gmail.com",
      "password": "cafecito456",
      "address": "Plaza Central 456",
      "time": "17-10-2023",
      "average_rating": 4.1,
      "rating": [],
      "contact": "1199776655",
      "payment": "Pago Online/Tarjeta",
      "image": null
    },
    {
      "name": "Sabores de México",
      "email": "saboresdemexico@gmail.com",
      "password": "mexicanos123",
      "address": "Calle Jalisco 789",
      "time": "18-10-2023",
      "average_rating": 4.4,
      "rating": [],
      "contact": "1144223366",
      "payment": "Efectivo",
      "image": null
    },
    {
      "name": "La Pizzería",
      "email": "lapizzeria@gmail.com",
      "password": "pizzalover456",
      "address": "Av. Napoli 123",
      "time": "19-10-2023",
      "average_rating": 4.0,
      "rating": [],
      "contact": "1122334455",
      "payment": "Pago Online/Tarjeta",
      "image": null
    }
  ]
  