module.exports= [
    {
      "name": "Vendedor 1",
      "email": "vendedor1@example.com",
      "password": "contrasena1",
      "address": "Dirección 1",
      "time": "Horario 1",
      "average_rating": 4.5,
      "rating": [4.0, 4.5, 5.0],
      "contact": "Contacto 1",
      "payment": ["Efectivo", "Pago Online/Tarjeta"],
      "image": "imagen1.jpg"
    },
    {
      "name": "Vendedor 2",
      "email": "vendedor2@example.com",
      "password": "contrasena2",
      "address": "Dirección 2",
      "time": "Horario 2",
      "average_rating": 3.7,
      "rating": [3.0, 4.0, 4.5],
      "contact": "Contacto 2",
      "payment": ["Efectivo"],
      "image": "imagen2.jpg"
    },
    {
      "name": "Vendedor 3",
      "email": "vendedor3@example.com",
      "password": "contrasena3",
      "address": "Dirección 3",
      "time": "Horario 3",
      "average_rating": 4.0,
      "rating": [4.0, 4.0, 4.0],
      "contact": "Contacto 3",
      "payment": ["Pago Online/Tarjeta"],
      "image": "imagen3.jpg"
    },
    {
      "name": "Vendedor 4",
      "email": "vendedor4@example.com",
      "password": "contrasena4",
      "address": "Dirección 4",
      "time": "Horario 4",
      "average_rating": 4.8,
      "rating": [5.0, 4.5, 5.0],
      "contact": "Contacto 4",
      "payment": ["Efectivo", "Pago Online/Tarjeta"],
      "image": "imagen4.jpg"
    },
    {
      "name": "Vendedor 5",
      "email": "vendedor5@example.com",
      "password": "contrasena5",
      "address": "Dirección 5",
      "time": "Horario 5",
      "average_rating": 3.2,
      "rating": [3.0, 3.5, 3.0],
      "contact": "Contacto 5",
      "payment": ["Efectivo"],
      "image": "imagen5.jpg"
    },
    {
      "name": "Vendedor 6",
      "email": "vendedor6@example.com",
      "password": "contrasena6",
      "address": "Dirección 6",
      "time": "Horario 6",
      "average_rating": 4.4,
      "rating": [4.5, 4.0, 4.5],
      "contact": "Contacto 6",
      "payment": ["Pago Online/Tarjeta"],
      "image": "imagen6.jpg"
    },
    {
      "name": "Vendedor 7",
      "email": "vendedor7@example.com",
      "password": "contrasena7",
      "address": "Dirección 7",
      "time": "Horario 7",
      "average_rating": 3.9,
      "rating": [3.5, 4.0, 4.0],
      "contact": "Contacto 7",
      "payment": ["Efectivo"],
      "image": "imagen7.jpg"
    },
    {
      "name": "Vendedor 8",
      "email": "vendedor8@example.com",
      "password": "contrasena8",
      "address": "Dirección 8",
      "time": "Horario 8",
      "average_rating": 4.7,
      "rating": [5.0, 4.5, 4.5],
      "contact": "Contacto 8",
      "payment": ["Pago Online/Tarjeta"],
      "image": "imagen8.jpg"
    },
    {
      "name": "Vendedor 9",
      "email": "vendedor9@example.com",
      "password": "contrasena9",
      "address": "Dirección 9",
      "time": "Horario 9",
      "average_rating": 4.2,
      "rating": [4.0, 4.5, 3.5],
      "contact": "Contacto 9",
      "payment": ["Efectivo"],
      "image": "imagen9.jpg"
    },
    {
      "name": "Vendedor 10",
      "email": "vendedor10@example.com",
      "password": "contrasena10",
      "address": "Dirección 10",
      "time": "Horario 10",
      "average_rating": 4.9,
      "rating": [5.0, 5.0, 4.5],
      "contact": "Contacto 10",
      "payment": ["Efectivo", "Pago Online/Tarjeta"],
      "image": "imagen10.jpg"
    }
  ]