
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_ALL_FAV = 'GET_ALL_FAV'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const POST_FAVORITES = 'POST_FAVORITES'
export const CREATE_USER = 'CREATE_USER'
export const GET_SELLER_FAV = 'GET_SELLER_FAV'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const CREATE_POST = 'CREATE_POST'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_SELLER_BY_ID = 'GET_SELLER_BY_ID'
export const GET_ALL_SELLERS = 'GET_ALL_SELLERS'
export const DELETE_SELLER = 'DELETE_SELLER'
export const UPDATE_SELLER = 'UPDATE_SELLER'
export const CREATE_SELLER = 'CREATE_SELLER'
export const GET_ALL_USER = 'GET_ALL_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const GET_POST = 'GET_POST'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'

export const PROVINCIAS = 'PROVINCIAS'
export const MUNICIPIOS = 'MUNICIPIOS'
export const LOCALIDADES = 'LOCALIDADES'

export const SEARCH_BY_ID = 'SEARCH_BY_ID';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';

export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const VERIFY_TOKEN = 'VERIFY_TOKEN'